### PR TITLE
Added instructions for initializing boot2docker with enough memory.

### PR DESCRIPTION
**Pull request by tlhampton13**
Added instructions for initializing boot2docker with enough memory.

### CODE REVIEW

**Comment by mrburrito** [comment]
Do we want to init with 10GB of RAM or is 4-8GB enough?

**Comment by tlhampton13** [comment]
I have no idea how much is enough. 10GB is what I tried initially and it worked for what I was testing at the time.

**Comment by tlhampton13** [comment]
I was able to successfully ingest & index the-movie-db example using 4GB of base memory assigned to boot2docker.   This may or may not be enough to run other tasks.

**Comment by mrburrito** [comment]
Lets drop it down to 4GB by default and let people know they can allocate more if necessary.

**Comment by tlhampton13** [comment]
Changed the base memory for boot2docker init to 4GB and noted that more can be configured as needed.

**Pull request merged**
