### PR TITLE
Adding extension point for a vertex menu

### PR DESCRIPTION
**Pull request by dcendents**
Hi,

We've added a new extension point to add menu items on a vertex.
It would be nice if it it could be merged in lumify.

Please let me know if you think it requires any amendment.

Thanks

### CODE REVIEW

**Comment by mrburrito** [comment]
Can you provide more detail in the documentation for each of the options (brief description of purpose, discussion of function arguments and expected return values) and some simple examples?

**Comment by dcendents** [comment]
Thanks for the feedback, I will add more documentation.

When you say you want some simple examples, do you want a working hello world plugin or you meant  some documentation in a README.md? I think the plugin would be better but I'm not sure if you want to start adding hello world plugins in the lumify source code.

**Comment by mrburrito** [comment]
Definitely add more details to the README file. I think adding an examples folder to the plugin with the Hello World source (guessing it would be a single file?) isn't a bad thing. It won't get compiled or deployed, but it's nice to have in the code base as a reference.

**Comment by dcendents** [comment]
sorry for the delay, I've improved the documentation and added a small example plugin which can be compiled with maven but is not part of the normal build.

I've also rebased it on the latest develop. Let me know what you think please.

**Comment by dcendents** [comment]
thanks

**Pull request merged**
